#ifndef TOKENCODES_H
#define TOKENCODES_H

enum TokenCodes
{
  IDENT, NUMLIT, PLUS, MINUS, TIMES, SLASH, REMSYM, TRUESYM, FALSESYM, NOTSYM,
  EQL, NEQ, LSS, LEQ, GTR, GEQ, LPAREN, RPAREN, COMMA, COLON, SEMICOLON,
  BECOMES, BEGINSYM, ENDSYM, IFSYM, THENSYM, ELSESYM, WHILESYM, LOOPSYM,
  GETSYM, PUTSYM, NEWLINE, NULLSYM, BOOLSYM, INTSYM, ISSYM, PROCSYM, NAL, EOI
};

#endif